config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/chargebee_data'
  devise_for :users

  resources :users, only: [:index] do 
    resources :user_subscriptions, only: [:index, :edit, :update]
  end

  resources :user_subscriptions, only: [] do 
    resources :user_subscription_items, only: [:index] 
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user_subscription.rb
class UserSubscription < ApplicationRecord
	has_many :user_subscription_items
	belongs_to :user
end

app/controllers/user_subscriptions_controller.rb
class UserSubscriptionsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @user_subscriptions = @user.user_subscriptions.all
  end

  def edit
    @user = User.find(params[:user_id])
    @user_subscription = UserSubscription.find(params[:id])
  end

  def update
    user_subscription = UserSubscription.find(params[:id])
    service = EditSubscriptionService.new(user_subscription, params).edit_subscription
    redirect_to users_path
  end
end

app/views/user_subscriptions/edit.html.erb
<h1>Chargebee Subscription</h1>

<p id="notice"><%= notice %></p>

<%= form_for([@user, @user_subscription]) do |f| %>
  <%= hidden_field :user_id, @user.id %>

  <div class="field">
    <%= f.label :current_term_start, "Date" %>
    <%= f.date_select :current_term_start, { required: true, class: "form-control" } %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Submit', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/user_subscriptions/index.html.erb
<h1><%= @user.first_name%>s' Susbcription List</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Subscription Id</th>
      <th scope="col">Billing Period</th>
      <th scope="col">Billing Period Unit</th>
      <th scope="col">Status</th>
      <th scope="col">Current Term Start</th>
      <th scope="col">Current Term End</th>
      <th scope="col">Next billing Time</th>
      <th scope="col">Activation Time</th>
      <th scope="col">Currency Code</th>
      <th scope="col">Channel</th>
      <th scope="col">Subscription Item List</th>
      <th scope="col">Change Plan</th>
    </tr>
  </thead>
  <tbody>
    <% @user_subscriptions.each_with_index do |subscription, index|%>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= subscription.subscription_id %></td>
        <td><%= subscription.billing_period %></td>
        <td><%= subscription.billing_period_unit %></td>
        <td><%= subscription.status %></td>
        <td><%= time_format(subscription.current_term_start)%></td>
        <td><%= time_format(subscription.current_term_end) %></td>
        <td><%= time_format(subscription.next_billing_at) %></td>
        <td><%= time_format(subscription.activated_at) %></td>
        <td><%= subscription.currency_code %></td>
        <td><%= subscription.channel %></td>
        <td>
          <% subscription.user_subscription_items.each do |item| %>
            <ul>
              <li><%= link_to item.item_price_id, user_subscription_user_subscription_items_path(item) %></li>
            </ul>
          <% end %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>