config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/chargebee_data'
  devise_for :users

  resources :users, only: [:index] do 
    resources :user_subscriptions, only: [:index, :edit, :update]
  end

  resources :user_subscriptions, only: [] do 
    resources :user_subscription_items, only: [:index] 
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_subscriptions
  has_many :user_plan_changes

  attr_accessor :skip_password_validation  # virtual attribute to skip password validation while saving

  protected

  def password_required?
    return false if skip_password_validation
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
end

app/views/users/index.html.erb
<h1>Users' List</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Customer ID</th>
      <th scope="col">Phone</th>
      <th scope="col">Comapny</th>
      <th scope="col">User Subscriptions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |user, index|%>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.customer_id %></td>
        <td><%= user.phone %></td>
        <td><%= user.company %></td>
        <td>
          <% user.user_subscriptions.each do |subscription| %>
            <ul>
              <li style="lin"><%= link_to subscription.subscription_id, user_user_subscriptions_path(user) %></li>
              <li><%= link_to "Update Plan", edit_user_user_subscription_path(user, subscription), class: "btn btn-sm btn-success" %></li>
            </ul>
          <% end %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<style type="text/css">
  ul {
  list-style-type: none;
}
</style>